# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd1feea60de6d0c64cf27f4667cc3f29c5c7bd55a74fbb781c4fab2e81a88d87f07518c7361517747e364fa62569b93c3bf737ad54f3f62169145650159491ff

test:
  secret_key_base: eb7a7e56fe23a8a770de6919812f66cce2a522e19f5833b44d2b6c66023e32afb55586ca3ea79c2a86e3efddb9e072509dbb487acdfcae7a008c1096056c576a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
